def run_sample_workload(cache):
    cache.add(1,2)
    cache.add(2,4)
    print(cache.cache)
    cache.add(2,3)
    print(cache.cache)
    cache.add(3,6)
    cache.add(4,8)
    cache.add(5,10)
    print(cache.cache)
    cache.add(6,12)
    print(cache.cache)
    cache.add(7,14)
    print(cache.cache)
    print(cache.get(3))
    print(cache.cache)
    cache.add(8,16)
    print(cache.cache)
